bind_port=29101
peers=192.168.0.104:29101
data_dir=/home/greendragon/Desktop/coin/src/data_seed
network_magic_hex=0x52504f57
duration_sec=0
autopropose=1
autopropose_interval_sec=3
public_endpoint=192.168.0.104:29101
